# Eager execution初探

tensorflow的eager execution模式可以在不构建图的情况下给出操作的执行结果，方便调试和验证代码
eager execution的例子：[eager execution的例子](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/eager/python/examples)

开启eager模式，需要将tf.enable_eager_execution()这句代码加到代码最前面，不要讲这句话加入到其他调用的模块中。

In [1]:
from __future__ import absolute_import, division, print_function
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
tf.executing_eagerly()

True

In [3]:
x = [[2.]]
m = tf.matmul(x, x)

In [4]:
print(m)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


在eager execution中可以使用numpy, numpy函数可以接受tf.Tensor参数，tf操作也可以接受numpy对象。tf.Tensor.numpy可以返回numpy对象

In [5]:
a = tf.constant([[1, 2], [3, 4]])

In [6]:
a

<tf.Tensor: id=4, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [8]:
print(a * b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [9]:
import numpy as np

In [10]:
c = np.multiply(a, b)

In [11]:
c

array([[ 2,  6],
       [12, 20]], dtype=int32)

In [12]:
print(a.numpy())

[[1 2]
 [3 4]]


In [13]:
d = tf.add(c, 1)

In [14]:
d

<tf.Tensor: id=16, shape=(2, 2), dtype=int32, numpy=
array([[ 3,  7],
       [13, 21]], dtype=int32)>