# dataset之data structure

一个dataset里面每个元素的结构都是一样的，每个元素包含一个或多个tensor，叫components，tensor中tf.DType,tf.TensorShape可以表示类型和形状。

Dataset.output_types和Dataset.output_shapes可以推断组件的类型和形状

In [1]:
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random_uniform([4, 10]))

In [3]:
dataset1.output_types

tf.float32

In [4]:
dataset1.output_shapes

TensorShape([Dimension(10)])

In [5]:
dataset2 = tf.data.Dataset.from_tensor_slices((
    tf.random_uniform([4]),
    tf.random_uniform([4, 100], maxval = 100, dtype = tf.int32)
))

In [6]:
dataset2.output_types

(tf.float32, tf.int32)

In [7]:
dataset2.output_shapes

(TensorShape([]), TensorShape([Dimension(100)]))

In [8]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

In [9]:
dataset3.output_types

(tf.float32, (tf.float32, tf.int32))

In [10]:
dataset3.output_shapes

(TensorShape([Dimension(10)]),
 (TensorShape([]), TensorShape([Dimension(100)])))

可以给每个component命名

In [11]:
dataset = tf.data.Dataset.from_tensor_slices({
    'a': tf.random_uniform([4]),
    'b': tf.random_uniform([4, 100], maxval = 100, dtype = tf.int32)
})

In [12]:
dataset.output_shapes

{'a': TensorShape([]), 'b': TensorShape([Dimension(100)])}

In [13]:
dataset.output_types

{'a': tf.float32, 'b': tf.int32}

对dataset里的每个元素可以使用map, flat_map, filter进行操作

In [14]:
dataset1 = dataset1.map(lambda x: x*2)

In [15]:
for x in dataset1:
    print(x)

Instructions for updating:
Colocations handled automatically by placer.
tf.Tensor(
[0.55495477 1.8403318  0.5232456  1.6476417  1.2926247  1.7027066
 1.7291434  1.1211901  0.5071373  1.2788341 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.00433588 1.57797    1.3726532  1.8247719  0.19171333 1.6345394
 0.01252842 1.1829517  0.10696292 0.751812  ], shape=(10,), dtype=float32)
tf.Tensor(
[1.8247073  1.408133   0.14770865 1.1271548  0.8116057  0.96690845
 1.4304702  0.01921916 0.75536346 0.38020635], shape=(10,), dtype=float32)
tf.Tensor(
[1.7528923  0.07332659 0.13496709 1.3140635  0.03167009 1.108294
 1.7367122  1.2901239  1.67222    0.766659  ], shape=(10,), dtype=float32)
